# Generated by Django 4.2.9 on 2024-01-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
